RESTORATOR
vasilro/summer-2019 pull request #2
Opened 2019-08-07 11:08 UTC by vasilro

## Номер
2033

## Номер задания
1

## Ссылка на видео с демо
https://www.youtube.com/watch?v=ecIWPzGEbFc

## Комментарии
Хотел сделать то-то, но не успел и не понимаю.

2019-08-07 11:10 UTC, vsevolod commented on 13/3/app/views/layout.erb
> +  <% if @flash_error %>
Выравнивание сделай нормальное

2019-08-07 12:07 UTC, vsevolod requested changes

2019-08-07 12:07 UTC, vsevolod commented on 13/3/app/views/layout.erb
> +        <div class="notification is-danger" style="max-width: 700px; margin: 1em auto 1em auto;">
Почему `is_danger` для notice?

2019-08-07 12:07 UTC, vsevolod commented on 13/3/app/views/layout.erb
> +          <%= flash[:notice] %>
`flash[type]`

2019-08-07 12:07 UTC, vsevolod commented on 13/3/app/views/place.erb
> +    <form action=<%= "/places/#{@place.id}/testimonials" %> method='post'>
Очень длинные `view`. Тебе нужно воспользоваться `partial`.
```ruby
<%= render 'testimonials/form' if current_user %>
```

2019-08-07 12:07 UTC, vsevolod commented on 13/3/app/views/place.erb
> +    <form action=<%= "/places/#{@place.id}/testimonials" %> method='post'>
И попробуй в другом месте вью тоже разбить по парчиалам

2019-08-07 12:07 UTC, vsevolod commented on 13/3/app/views/sign_up.erb
> +        <input class="input" type="text" name="name" placeholder="Text input" value=<% if @new_user%>"<%= @new_user.name%>" <%end%>>
Воспользуйся тернарным оператором

2019-08-09 08:15 UTC, vsevolod commented on 13/3/app/views/sign_up.erb
> +        <input class="input" type="text" name="name" placeholder="Text input" value=<% if @new_user%>"<%= @new_user.name%>" <%end%>>
`@new_user&.name`

2019-08-09 12:27 UTC, vsevolod requested changes

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/controllers/sessions_controller.rb
> +      @flash_error = 'Invalid email/password combo!'
Это уже не `flash` ошибка

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/views/layout.erb
> +    <% if type == :notice %>
Если у тебя `notice` проверяется только, то ты можешь убрать верхний `each` и проверять `flash[:notice]`

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/views/testimonials/form.erb
> +    <%= @testimonial_text %>
выравнивание

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/controllers/testimonials_controller.rb
>      @testimonial_text = params[:testimonial_text]
params и без этого прокидывается во view. Нет смысла создавать тут `@terstimonial_text`

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/views/testimonials/form.erb
> +  <textarea class="textarea" name="testimonial_text" placeholder="Ваш отзыв">
А в textarea разве нет параметра `value`?

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/views/testimonials/all_testimonials.erb
> +<% testimonials = @place.testimonials.includes(:user) %>
А вот тут надо этот код перенести в контроллер: `@testimonials = ...`

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/views/layout.erb
>    <div class="container">
Вынести в partial header

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/views/layout.erb
>    <div class="container">
Если делать без partial, выходит код (даже html код), который очень трудно читать. partial помогают логически разбивать его

2019-08-09 12:27 UTC, vsevolod commented on 13/3/app/controllers/users_controller.rb
> +      @flash_error = @new_user.errors.full_messages.join('; ')
Тоже не нравится название `@flash`

2019-08-09 14:07 UTC, vsevolod requested changes

2019-08-09 14:07 UTC, vsevolod commented on 13/3/app/controllers/places_controller.rb
>      @average_rating = @average_rating.round 2 if @average_rating
`round(2)` - скобки нужны если это не dsl

2019-08-09 14:07 UTC, vsevolod commented on 13/3/app/controllers/places_controller.rb
>      @average_rating = @average_rating.round 2 if @average_rating
А что - `@average_rating` он может быть nil?

2019-08-09 14:07 UTC, vsevolod commented on 13/3/app/controllers/testimonials_controller.rb
>      unless new_testimonial.save
https://github.com/rubocop-hq/ruby-style-guide#no-else-with-unless

2019-08-09 14:07 UTC, vsevolod commented on 13/3/app/views/header.erb
> +              Hey,&nbsp; <b><%= current_user.name %></b> &nbsp;&nbsp;
отступы внутри блока

2019-08-09 14:07 UTC, vsevolod commented on 13/3/app/views/layout.erb
> +      <div class="container">
Отступы

2019-08-09 14:07 UTC, vsevolod commented on 13/3/app/views/layout.erb
> +      <div class="container">
отступы

2019-08-09 14:18 UTC, vasilro commented on 13/3/app/controllers/places_controller.rb
>      @average_rating = @average_rating.round 2 if @average_rating
он nil, если нет отзывов

2019-08-09 14:39 UTC, vsevolod approved these changes

2019-08-11 13:02 UTC, merged